name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run linting
      run: |
        flake8 app/ tests/ --max-line-length=88 --extend-ignore=E203,W503
        black --check app/ tests/

    - name: Run unit tests
      run: |
        python -m pytest tests/unit/ -v --cov=app --cov-report=xml

    - name: Run integration tests
      run: |
        python -m pytest tests/integration/ -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  docker-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t sentiment-analysis-api:test .

    - name: Test Docker image
      run: |
        docker run -d --name test-api -p 8000:8000 sentiment-analysis-api:test
        sleep 15
        curl -f http://localhost:8000/health || (docker logs test-api && exit 1)
        curl -f -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{"text": "I love this product!"}' || (docker logs test-api && exit 1)
        docker stop test-api && docker rm test-api 